config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations/registrations' }
  resources :users do
    resources :ingredients
  end
  root 'static_pages#home'

end

app/models/expiration_date.rb
class ExpirationDate < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :food_type
  has_many :ingredients, dependent: :destroy
  validates :name, presence: true
  validate :at_least_one_duration

  def at_least_one_duration
    errors.add(:base, 'Duration must be specified for freezer or fridge.') unless freezer_duration | fridge_duration
  end
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :expiration_dates
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
  belongs_to :expiration_date
  default_scope -> { order(created_at: :asc) }
  validates :user, presence: true
  validates :expiration_date, presence: true
  validates :name, presence: true
  validate :purchase_date_cannot_be_in_the_future

  def expired?
    self.in_freezer ? Time.now > (purchase_date + expiration_date.freezer_duration.seconds) :
        Time.now > (purchase_date + expiration_date.fridge_duration.seconds)
  end

  def expires_on
    self.in_freezer ? purchase_date + expiration_date.freezer_duration.seconds :
        purchase_date + expiration_date.fridge_duration.seconds
  end

  def expires_on_formatted
    self.expires_on.strftime("%b %d, %Y")
  end

  def time_until_expiration_in_words
    self.in_freezer ? distance_of_time_in_words(purchase_date, Time.now - expiration_date.freezer_duration.days) :
        distance_of_time_in_words(purchase_date, Time.now - expiration_date.fridge_duration.days)
  end

  protected

    def purchase_date_cannot_be_in_the_future
      if purchase_date > Time.now
        errors.add(:purchase_date, "can't be in the future")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ingredients, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected

    def after_sign_in_path_for(resource)
      root_path   # Always redirect to home page after sign in.
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  around_filter :set_time_zone

  def create
    @ingredient = current_user.ingredients.build(ingredient_params)

    if @ingredient.save
      flash[:success] = "Ingredient added"

      # This should redirect to the page that the ingredient was created on.
      redirect_to current_user
    else
      @user = current_user
      render 'users/show'
    end
  end

  def destroy
    # TODO: ensure ingredient to be deleted belongs to this user!
    @user = User.find(params[:user_id])
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.destroy
      flash[:success] = "Ingredient deleted"
      redirect_to @user
    end
  end

  private

    def ingredient_params
      params.require(:ingredient).permit([:name, :expiration_date_id, :purchase_date, :in_freezer])
    end

    def set_time_zone
      old_tz = Time.zone
      Time.zone = current_user.timezone unless current_user.nil?
      yield
    ensure
      Time.zone = old_tz
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @ingredients = @user.ingredients
    @ingredient = current_user.ingredients.build

    # Uncomment to only give access to logged in user's page
    # unless @user == current_user
    #   redirect_to :back, alert: 'Access denied.'
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

  # TZ conversion may be unnecessary here.
  def time_left_in_days(ingredient)
    ((ingredient.purchase_date.in_time_zone(current_user.timezone) +
        ingredient.expiration_date.duration.days - Time.now.in_time_zone(current_user.timezone)) /
        1.day).round(2)
  end

  def format_datetime(ts)
    ts.in_time_zone(current_user.timezone).strftime("%m-%-d-%Y")
  end

  def format_datetime_precise(ts)
    ts.in_time_zone(current_user.timezone).strftime("%m-%-d-%Y %I:%M %p")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/_ingredient.html.erb
<!-- UNUSED, see users/show.html -->
<li id="ingredient-<%= ingredient.id %>">
  <span class="name"><%= ingredient.name %></span>
  <span class="expiration_date_name">Type: <%= ingredient.expiration_date.name %></span>
  <span class="expiration_date_duration">Time left: <%= ingredient.expiration_date.duration.days - (Time.now - ingredient.purchase_date) %></span>
</li>

app/views/ingredients/_ingredient_form.html.erb
<%= form_for [@user, @ingredient] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :ingredient_name %>
    <%= f.text_field :name, placeholder: 'Enter a name for this ingredient (ex. leftover porkchops)' %>
  </div>
  <div class="field">
    <%= f.label :ingredient_type %>
    <%= f.collection_select :expiration_date_id, ExpirationDate.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :frozen? %>
    <%= f.check_box :in_freezer, html_options = {class: 'checkbox'} %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %>
    <%= f.datetime_select :purchase_date, ampm: true, default: 0.days.from_now.in_time_zone(current_user.timezone) %>
  </div>
  <%= f.submit 'Add Ingredient', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pantry by Pixel Cartel
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "pantry", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="nonlink"><%= current_user.email %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Pantry</title>
      <%= stylesheet_link_tag 'application', media: 'all',
                              'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
          <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Pantry</h1>

  <h2>
    Pantry helps you make use of your foodstuffs before they go bad.
  </h2>

  <% if user_signed_in? %>
      <%= link_to "Go to your pantry!", user_path(current_user), class: "btn btn-lg btn-primary" %>
  <% else %>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("http://rubyonrails.org/images/rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>
<p>Timezone: <%= @user.timezone %></p>

<div>
  <% if @user.ingredients.any? %>
    <h3>Ingredients (<%= @user.ingredients.count %>)</h3>
    <ul class="ingredients">
      <table class="table">
        <thead>
        <td></td>
        <td>Ingredient Name</td>
        <td>Ingredient Type</td>
        <td>Storage</td>
        <td>Expires</td>
        <td>Purchased</td>
        <td>Entry Created</td>
        <td>Entry Modified</td>
        </thead>
        <% @user.ingredients.each do |ingredient| %>
          <% if ingredient.valid? %>
            <tr>
              <td><%= button_to 'Delete', [@user, ingredient], method: :delete,
                                confirm: "Confirm deletion", class: "btn btn-danger" %></td>
              <td><%= ingredient.name %></td>
              <td><%= ingredient.expiration_date.name %></td>
              <% unless ingredient.in_freezer %>
                <td>Fridge</td>
              <% else %>
                <td>Freezer</td>
              <% end %>
              <td>
                <% if ingredient.expired? %>
                  <span class="bg-danger">Expired</span>
                <% else %>
                  <%= time_ago_in_words(ingredient.expires_on) %>
                <% end %>
              </td>
              <td><%= time_ago_in_words(ingredient.purchase_date.in_time_zone(current_user.timezone)) %> ago</td>
              <td>
                <% unless ingredient.created_at.blank? %>
                  <%= format_datetime_precise ingredient.created_at %>
                <% end %>
              </td>
              <td>
                <% unless ingredient.updated_at.blank? %>
                  <%= format_datetime_precise ingredient.updated_at %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </ul>
  <% end %>
  <div>
    <section class="ingredient_form">
      <%= render 'ingredients/ingredient_form' %>
    </section>
  </div>
</div>